### ISSUE TITLE
Issue with updating Drupal WxT from 2.109 to 2.213 

### ISSUE THREAD

**Issue by PCH-TanB** [drupalwxt/wxt#149] opened 2019-03-11 18:48 UTC
I have an issue with updating Drupal WxT from 2.109 to 2.213 by following https://www.drupal.org/docs/8/update/update-core-manually as below:
1. Turn on maintenance mode
2. Navigate into my wxt-8.x-2.109.
cd /sites/intra/htdocs/wxt-8.x-2.109
3. Remove the 'core' and 'vendor' directories.
rm -rf core vendor
4. Remove all of the files in the top-level directory.
rm -f *.* .[a-z]*
5.  Copy the 'core' and 'vendor' directory and the files in the top-level directory from wxt-8.x-2.213 into wxt-8.x-2.109:
cd ../drupalwxt/wxt-8.x-2.213
cp -R core vendor  /sites/intra/htdocs/wxt-8.x-2.109/
cp *.* .[a-z]* /sites/intra/htdocs/wxt-8.x-2.109/
6. from browser to run: http://pchintradev.in.pch.gc.ca/wxt-8.x-2.109/update.php
Then I got the following error:
The website encountered an unexpected error. Please try again later.
Drupal\Core\Extension\Exception\UnknownExtensionException: The profile Array does not exist. in Drupal\Core\Extension\ExtensionList->get() (line 257 of core/lib/Drupal/Core/Extension/ExtensionList.php).
Could you please help me with this? Thanks a lot!

**Comment by PCH-TanB** [comment] 2019-03-12 13:30
By following the professional suggestion from Zachary Seguin to inlcude **modules, libraries, themes and  profiles** directories on steps 3 and 5, now the updating is done only with a failure of extra_fields updating:
system module
Update extra_fields
•	Failed: Drupal\Component\Plugin\Exception\PluginNotFoundException: The "image_immutable" plugin does not exist. in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 52 of /sites/intra/htdocs/wxt-8.x-2.109/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).

**Comment by sylus** [comment] 2019-03-26 02:09
I don't suppose there is a way can see the db of this upgrade?

I've tried by installing the 2.109 update and then creating some content, then upgrading to 2.213 but couldn't reproduce issue.

That being said and vageuly remember this type of issue in the passed. Will check a few issues.

**Comment by RabiaSajjad** [comment] 2019-03-26 04:09
I encountered this issue and fixed using the following:
 
`drush php-eval 'module_load_include('install',
'lightning_media'); print lightning_media_update_8017()'; drush cr; `

**Comment by PCH-TanB** [comment] 2019-03-26 12:42
@RabiaSajjad 
I followed your instructions to run your fix, but I got the following error:
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /sites/intra/htdocs/wxt-8.x-2.109/core/lib/Drupal/Core/DrupalKernel.php on line 495
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                  [error]
Error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in
/sites/intra/htdocs/wxt-8.x-2.109/core/lib/Drupal/Core/DrupalKernel.php, line 495
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /sites/intra/htdocs/wxt-8.x-2.109/core/lib/Drupal/Core/DrupalKernel.php on line 495
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                  [error]
Error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in
/sites/intra/htdocs/wxt-8.x-2.109/core/lib/Drupal/Core/DrupalKernel.php, line 495

![image](https://user-images.githubusercontent.com/2203586/54997862-17daf580-4fa3-11e9-8e01-5c54b1a144f2.png)

**Comment by PCH-TanB** [comment] 2019-03-26 12:51
my PHP Version is 7.1.8

**Comment by RabiaSajjad** [comment] 2019-03-26 13:23
Try changing the outer-most quotes:

`drush php-eval "module_load_include('install', 'lightning_media'); print lightning_media_update_8017()"; drush cr;`

**Comment by PCH-TanB** [comment] 2019-03-26 13:41
@RabiaSajjad 
I got the same error:

![image](https://user-images.githubusercontent.com/2203586/55001609-5b396200-4fab-11e9-8088-17b9b693352a.png)

**Comment by sylus** [comment] 2019-09-09 01:18
Hey am closing this out since has been a while, hopefully this issue was solved  between one of the new releases. If is still a problem please file an issue over at drupal.org/project/wxt.

Unfortunately we would need clear replication steps, but happy to take a look.

**Closed as completed by sylus** 2019-09-09 01:18 UTC
